/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import br.com.integrador.dao.ClienteDao;
import br.com.integrador.dao.EnderecoDao;
import br.com.integrador.dao.TelefoneDao;
import br.com.integrador.execao.TratamentoDeErros;
import br.com.integrador.modelos.Cliente;
import br.com.integrador.modelos.Endereco;
import br.com.integrador.modelos.Telefone;
import java.sql.Date;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Estefania
 */
public final class AlterarCliente extends javax.swing.JFrame {

    /**
     * Creates new form alterarCliente
     */
    ClienteDao clientes = new ClienteDao();
    EnderecoDao e = new EnderecoDao();

    private final Cliente cliente;

    public AlterarCliente(Cliente umCliente) {
        this.cliente = umCliente;

        initComponents();
        carregarCamposTela();

        setExtendedState(AlterarCliente.MAXIMIZED_BOTH);

    }

    public void carregarCamposTela() {
        this.id.setText(String.valueOf(this.cliente.getIdCliente()));
        this.campoNome.setText(this.cliente.getNome());
        this.campoEmail.setText(this.cliente.getEmail());
        this.campoEndereco.setText(this.cliente.getEndereco().getRua());
        this.campoCep.setText(String.valueOf(this.cliente.getEndereco().getCep()));
        this.campoNumero.setText(this.cliente.getEndereco().getNumero());
        this.campoBairro.setText(this.cliente.getEndereco().getBairro());
        this.campoComplemento.setText(String.valueOf(this.cliente.getEndereco().getComplemento()));
        this.campoTelefone.setText(this.cliente.getTelefones().get(0).toString());
        Date dataCliente = cliente.getDataNascimento();
        int dia = dataCliente.getDay();
        int mes = dataCliente.getMonth();
        int ano = dataCliente.getYear();
        this.data.setSelectedItem(dia);
        this.mes.setSelectedIndex(mes);
        this.ano.setSelectedItem(ano);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeClienteAlterar = new javax.swing.JLabel();
        bairro = new javax.swing.JLabel();
        complemento = new javax.swing.JLabel();
        dataNasc = new javax.swing.JLabel();
        endereco = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        cep = new javax.swing.JLabel();
        numero = new javax.swing.JLabel();
        dataNacs2 = new javax.swing.JLabel();
        telefone = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        campoEmail = new javax.swing.JTextField();
        campoEndereco = new javax.swing.JTextField();
        campoBairro = new javax.swing.JTextField();
        campoNumero = new javax.swing.JTextField();
        campoCep = new javax.swing.JTextField();
        campoTelefone = new javax.swing.JTextField();
        campoComplemento = new javax.swing.JTextField();
        data = new javax.swing.JComboBox();
        mes = new javax.swing.JComboBox();
        ano = new javax.swing.JComboBox();
        alterar = new javax.swing.JButton();
        id = new javax.swing.JTextField();
        idCliente = new javax.swing.JLabel();
        voltarAoMenu3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        nomeClienteAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/NOME.png"))); // NOI18N
        getContentPane().add(nomeClienteAlterar);
        nomeClienteAlterar.setBounds(130, 270, 80, 40);

        bairro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/BAIRRO.png"))); // NOI18N
        getContentPane().add(bairro);
        bairro.setBounds(130, 410, 90, 40);

        complemento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/COMPLEMENTO.png"))); // NOI18N
        getContentPane().add(complemento);
        complemento.setBounds(830, 370, 180, 30);

        dataNasc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/NASCIMENTO.png"))); // NOI18N
        getContentPane().add(dataNasc);
        dataNasc.setBounds(130, 470, 120, 30);

        endereco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/ENDEREÇO.png"))); // NOI18N
        getContentPane().add(endereco);
        endereco.setBounds(130, 360, 132, 40);

        email.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/EMAIL.png"))); // NOI18N
        getContentPane().add(email);
        email.setBounds(130, 310, 70, 40);

        cep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/CEP.png"))); // NOI18N
        getContentPane().add(cep);
        cep.setBounds(940, 410, 60, 40);

        numero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/NUMERO.png"))); // NOI18N
        getContentPane().add(numero);
        numero.setBounds(570, 360, 110, 40);

        dataNacs2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/NASCIMENTO2.png"))); // NOI18N
        getContentPane().add(dataNacs2);
        dataNacs2.setBounds(250, 470, 164, 40);

        telefone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/TELEFONE.png"))); // NOI18N
        getContentPane().add(telefone);
        telefone.setBounds(840, 280, 110, 30);
        getContentPane().add(campoNome);
        campoNome.setBounds(220, 280, 600, 30);
        getContentPane().add(campoEmail);
        campoEmail.setBounds(230, 320, 1070, 30);
        getContentPane().add(campoEndereco);
        campoEndereco.setBounds(270, 370, 290, 30);
        getContentPane().add(campoBairro);
        campoBairro.setBounds(240, 420, 690, 30);
        getContentPane().add(campoNumero);
        campoNumero.setBounds(690, 370, 120, 30);

        campoCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCepActionPerformed(evt);
            }
        });
        getContentPane().add(campoCep);
        campoCep.setBounds(1010, 420, 290, 30);
        getContentPane().add(campoTelefone);
        campoTelefone.setBounds(960, 280, 340, 30);
        getContentPane().add(campoComplemento);
        campoComplemento.setBounds(1030, 370, 270, 30);

        data.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(data);
        data.setBounds(430, 470, 60, 30);

        mes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        getContentPane().add(mes);
        mes.setBounds(490, 470, 130, 30);

        ano.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1915", "1916", "1917", "1918", "1919", "1920", "1921", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015" }));
        getContentPane().add(ano);
        ano.setBounds(620, 470, 110, 30);

        alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotoes/alterarCliente.png"))); // NOI18N
        alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarActionPerformed(evt);
            }
        });
        getContentPane().add(alterar);
        alterar.setBounds(980, 560, 190, 40);

        id.setEditable(false);
        getContentPane().add(id);
        id.setBounds(230, 230, 40, 30);

        idCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        idCliente.setText("ID");
        getContentPane().add(idCliente);
        idCliente.setBounds(150, 230, 40, 30);

        voltarAoMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotoes/VoltarAoMenuBotao.png"))); // NOI18N
        voltarAoMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarAoMenu3ActionPerformed(evt);
            }
        });
        getContentPane().add(voltarAoMenu3);
        voltarAoMenu3.setBounds(170, 560, 190, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/background2.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-20, 0, 1650, 850);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCepActionPerformed

    private void alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarActionPerformed

        EnderecoDao endereco = new EnderecoDao();
        ClienteDao client = new ClienteDao();
        TelefoneDao telefone = new TelefoneDao();
        TratamentoDeErros tratamentoDeErros = new TratamentoDeErros();

        Endereco meuEndereco = new Endereco(this.campoEndereco.getText(), this.campoBairro.getText(), Integer.parseInt(this.campoCep.getText()), this.campoComplemento.getText(), this.campoNumero.getText());
        int idEndereco = client.consultarporIdParaAtualizarEndereco(Integer.parseInt(this.id.getText()));
        meuEndereco.setIdEndereco(idEndereco);
        endereco.alterarUmEndereco(meuEndereco);
        tratamentoDeErros.TestarExecao(idEndereco);

        if (idEndereco > 0) {
            Telefone meuTelefone = new Telefone(Integer.parseInt(this.campoTelefone.getText()));
            int idTelefone = telefone.consultarporIdParaAtualizarTelefone(Integer.parseInt(this.id.getText()));
            meuTelefone.setIdTelefone(idTelefone);
            telefone.alterarUmTelefone(meuTelefone);
            tratamentoDeErros.TestarExecao(idTelefone);

            if (idTelefone > 0) {
                java.util.Date DataInformada = new java.util.Date(Integer.parseInt(this.ano.getSelectedItem().toString()) - 1900, this.mes.getSelectedIndex(), Integer.parseInt(this.data.getSelectedItem().toString()));
                java.sql.Date dataFinal = new java.sql.Date(DataInformada.getTime());

                Cliente meuCliente = new Cliente(this.campoNome.getText(), dataFinal, this.campoEmail.getText(), meuEndereco, Arrays.asList(meuTelefone));
                int idCli = client.consultarporIdParaAtualizarCliente(Integer.parseInt(this.id.getText()));
                meuCliente.setIdCliente(idCli);
                client.alterarUmCliente(meuCliente);
                tratamentoDeErros.TestarExecao(idCli);

                if (idCli > 0) {

                    JOptionPane.showMessageDialog(this, "Cliente alterado com sucesso", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Falha ao alterar o Cliente", "Sucesso", JOptionPane.ERROR_MESSAGE);
                }

            }
        }

    }//GEN-LAST:event_alterarActionPerformed

    private void voltarAoMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarAoMenu3ActionPerformed
        new PaginaInicialRevendedora().setVisible(true);
        dispose();
    }//GEN-LAST:event_voltarAoMenu3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterar;
    private javax.swing.JComboBox ano;
    private javax.swing.JLabel bairro;
    private javax.swing.JTextField campoBairro;
    private javax.swing.JTextField campoCep;
    private javax.swing.JTextField campoComplemento;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoEndereco;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoNumero;
    private javax.swing.JTextField campoTelefone;
    private javax.swing.JLabel cep;
    private javax.swing.JLabel complemento;
    private javax.swing.JComboBox data;
    private javax.swing.JLabel dataNacs2;
    private javax.swing.JLabel dataNasc;
    private javax.swing.JLabel email;
    private javax.swing.JLabel endereco;
    private javax.swing.JTextField id;
    private javax.swing.JLabel idCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox mes;
    private javax.swing.JLabel nomeClienteAlterar;
    private javax.swing.JLabel numero;
    private javax.swing.JLabel telefone;
    private javax.swing.JButton voltarAoMenu3;
    // End of variables declaration//GEN-END:variables

}
