/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import br.com.integrador.dao.EnderecoDao;
import br.com.integrador.dao.FornecedorDao;
import br.com.integrador.dao.TelefoneDao;
import br.com.integrador.execao.TratamentoDeErros;
import br.com.integrador.modelos.Endereco;
import br.com.integrador.modelos.Fornecedor;
import br.com.integrador.modelos.Telefone;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Estefania
 *
 */
public class AlterarFornecedor extends javax.swing.JFrame {

    /**
     * Creates new form AlterarFornecedor
     */
    FornecedorDao fornecedores = new FornecedorDao();
    EnderecoDao e = new EnderecoDao();

    private Fornecedor fornecedor;

    private final DefaultTableModel modelo = new DefaultTableModel();

    public AlterarFornecedor(Fornecedor umFornecedor) {

        this.fornecedor = umFornecedor;

        initComponents();
        carregarTabela();

        setExtendedState(AlterarFornecedor.MAXIMIZED_BOTH);

    }

    public void carregarTabela() {
        this.id.setText(String.valueOf(this.fornecedor.getIdFornecedor()));
        this.campoNome.setText(this.fornecedor.getNome());
        this.campoEmail.setText(this.fornecedor.getEmail());
        this.campoEndereco.setText(this.fornecedor.getEndereco().getRua());
        this.campoCep.setText(String.valueOf(this.fornecedor.getEndereco().getCep()));
        this.campoNumero.setText(this.fornecedor.getEndereco().getNumero());
        this.campoBairro.setText(this.fornecedor.getEndereco().getBairro());
        this.campoComplemento.setText(String.valueOf(this.fornecedor.getEndereco().getComplemento()));
        this.campoTelefone.setText(this.fornecedor.getTelefones().get(0).toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        nome = new javax.swing.JLabel();
        endereço = new javax.swing.JLabel();
        complemento = new javax.swing.JLabel();
        bairro = new javax.swing.JLabel();
        telefone = new javax.swing.JLabel();
        numero = new javax.swing.JLabel();
        cep = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        campoEmail = new javax.swing.JTextField();
        campoEndereco = new javax.swing.JTextField();
        campoComplemento = new javax.swing.JTextField();
        campoBairro = new javax.swing.JTextField();
        campoTelefone = new javax.swing.JTextField();
        campoCep = new javax.swing.JTextField();
        campoNumero = new javax.swing.JTextField();
        alterar = new javax.swing.JButton();
        id = new javax.swing.JTextField();
        voltarAoMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/titulos/alterarfornecedor.png"))); // NOI18N
        getContentPane().add(titulo);
        titulo.setBounds(370, 50, 600, 130);

        email.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/EMAIL.png"))); // NOI18N
        getContentPane().add(email);
        email.setBounds(360, 310, 90, 30);

        nome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/NOME.png"))); // NOI18N
        getContentPane().add(nome);
        nome.setBounds(360, 250, 80, 60);

        endereço.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/ENDEREÇO.png"))); // NOI18N
        getContentPane().add(endereço);
        endereço.setBounds(360, 350, 130, 30);

        complemento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/COMPLEMENTO.png"))); // NOI18N
        getContentPane().add(complemento);
        complemento.setBounds(360, 390, 180, 30);

        bairro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/BAIRRO.png"))); // NOI18N
        getContentPane().add(bairro);
        bairro.setBounds(360, 430, 100, 33);

        telefone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/TELEFONE.png"))); // NOI18N
        getContentPane().add(telefone);
        telefone.setBounds(360, 470, 110, 50);

        numero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/NUMERO.png"))); // NOI18N
        getContentPane().add(numero);
        numero.setBounds(820, 350, 110, 30);

        cep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/CEP.png"))); // NOI18N
        getContentPane().add(cep);
        cep.setBounds(810, 380, 70, 40);

        campoNome.setBackground(java.awt.SystemColor.control);
        getContentPane().add(campoNome);
        campoNome.setBounds(450, 270, 670, 30);

        campoEmail.setBackground(java.awt.SystemColor.control);
        getContentPane().add(campoEmail);
        campoEmail.setBounds(450, 310, 670, 30);

        campoEndereco.setBackground(java.awt.SystemColor.control);
        getContentPane().add(campoEndereco);
        campoEndereco.setBounds(510, 350, 300, 30);

        campoComplemento.setBackground(java.awt.SystemColor.control);
        getContentPane().add(campoComplemento);
        campoComplemento.setBounds(560, 390, 240, 30);

        campoBairro.setBackground(java.awt.SystemColor.control);
        getContentPane().add(campoBairro);
        campoBairro.setBounds(470, 430, 650, 30);

        campoTelefone.setBackground(java.awt.SystemColor.control);
        getContentPane().add(campoTelefone);
        campoTelefone.setBounds(490, 480, 630, 30);

        campoCep.setBackground(java.awt.SystemColor.control);
        getContentPane().add(campoCep);
        campoCep.setBounds(880, 390, 240, 30);

        campoNumero.setBackground(java.awt.SystemColor.control);
        campoNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNumeroActionPerformed(evt);
            }
        });
        getContentPane().add(campoNumero);
        campoNumero.setBounds(940, 350, 180, 30);

        alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotoes/alterarf.png"))); // NOI18N
        alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarActionPerformed(evt);
            }
        });
        getContentPane().add(alterar);
        alterar.setBounds(1020, 560, 220, 40);

        id.setEditable(false);
        getContentPane().add(id);
        id.setBounds(710, 210, 40, 30);

        voltarAoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotoes/VoltarAoMenuBotao.png"))); // NOI18N
        voltarAoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarAoMenuActionPerformed(evt);
            }
        });
        getContentPane().add(voltarAoMenu);
        voltarAoMenu.setBounds(130, 570, 190, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/background2.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -60, 1730, 950);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNumeroActionPerformed

    private void alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarActionPerformed

        EnderecoDao dao = new EnderecoDao();
        FornecedorDao fornecedor = new FornecedorDao();
        TelefoneDao telefoneDao = new TelefoneDao();
        TratamentoDeErros tratamentoDeErros = new TratamentoDeErros();

        Endereco meuEndereco = new Endereco(this.campoEndereco.getText(), this.campoBairro.getText(), Integer.parseInt(this.campoCep.getText()), this.campoComplemento.getText(), this.campoNumero.getText());
        int idEndereco = fornecedor.consultarporIdParaAtualizarEnderecoDoFornecedor(Integer.parseInt(this.id.getText()));
        meuEndereco.setIdEndereco(idEndereco);
        dao.alterarUmEndereco(meuEndereco);
        tratamentoDeErros.TestarExecao(idEndereco);
       
        if (idEndereco > 0) {
            Telefone meuTelefone = new Telefone(Integer.parseInt(this.campoTelefone.getText()));
            int idTelefone = telefoneDao.consultarporIdParaAtualizarTelefoneDoFornecedor(Integer.parseInt(this.id.getText()));
            meuTelefone.setIdTelefone(idTelefone);
            telefoneDao.alterarUmTelefone(meuTelefone);
            tratamentoDeErros.TestarExecao(idTelefone);

            if (idTelefone > 0) {
                Fornecedor meuFornecedor = new Fornecedor(this.campoNome.getText(), this.campoEmail.getText(), meuEndereco, Arrays.asList(meuTelefone));
                int idFornecedor = fornecedor.consultarporIdParaAtualizarFornecedor(Integer.parseInt(this.id.getText()));
                meuFornecedor.setIdFornecedor(idFornecedor);
                fornecedor.alterarUmFornecedor(meuFornecedor);
                tratamentoDeErros.TestarExecao(idFornecedor);

                if (idFornecedor > 0) {
                    JOptionPane.showMessageDialog(this, "Fornecedor Alterado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

                } else {
                    JOptionPane.showMessageDialog(this, "Falha ao alterar o fornecedor =( ", "Error", JOptionPane.ERROR_MESSAGE);

                }

            }

        }

    }//GEN-LAST:event_alterarActionPerformed

    private void voltarAoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarAoMenuActionPerformed
        new PaginaInicialRevendedora().setVisible(true);
        dispose();
    }//GEN-LAST:event_voltarAoMenuActionPerformed

    /**
     * }
     *
     *
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterar;
    private javax.swing.JLabel bairro;
    private javax.swing.JTextField campoBairro;
    private javax.swing.JTextField campoCep;
    private javax.swing.JTextField campoComplemento;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoEndereco;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoNumero;
    private javax.swing.JTextField campoTelefone;
    private javax.swing.JLabel cep;
    private javax.swing.JLabel complemento;
    private javax.swing.JLabel email;
    private javax.swing.JLabel endereço;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nome;
    private javax.swing.JLabel numero;
    private javax.swing.JLabel telefone;
    private javax.swing.JLabel titulo;
    private javax.swing.JButton voltarAoMenu;
    // End of variables declaration//GEN-END:variables
}
