/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import br.com.integrador.dao.ClienteDao;
import br.com.integrador.dao.EnderecoDao;
import br.com.integrador.dao.TelefoneDao;
import br.com.integrador.execao.TratamentoDeErros;
import br.com.integrador.modelos.Cliente;
import br.com.integrador.modelos.Endereco;
import br.com.integrador.modelos.Telefone;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Estefania
 */
public class CadastrarCliente extends javax.swing.JFrame {
   
    /**
     * Creates new form CadastrarCliente
     */
    public CadastrarCliente() {
        initComponents();
        

        setExtendedState(CadastrarCliente.MAXIMIZED_BOTH);
    }
    
    public void limparTela(){
        nome.setText("");
        email.setText("");
        endereco.setText("");
        complemento.setText("");
        telefone.setText("");
        cep.setText("");
        numero.setText("");
        bairro.setText("");
       
       
        
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        campoNome = new javax.swing.JLabel();
        campoEmail = new javax.swing.JLabel();
        campoEndereco = new javax.swing.JLabel();
        campoCep = new javax.swing.JLabel();
        campoBairro = new javax.swing.JLabel();
        campoNumero = new javax.swing.JLabel();
        campoComplemento = new javax.swing.JLabel();
        campoTelefone = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        endereco = new javax.swing.JTextField();
        bairro = new javax.swing.JTextField();
        complemento = new javax.swing.JTextField();
        numero = new javax.swing.JTextField();
        cep = new javax.swing.JTextField();
        telefone = new javax.swing.JTextField();
        datadeNascimento = new javax.swing.JLabel();
        datadeNascimento2 = new javax.swing.JLabel();
        data = new javax.swing.JComboBox();
        mes = new javax.swing.JComboBox();
        ano = new javax.swing.JComboBox();
        voltarAoMenu = new javax.swing.JButton();
        cadastrar = new javax.swing.JButton();
        ativo = new javax.swing.JRadioButton();
        naoAtivo = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(745, 655));
        setMinimumSize(new java.awt.Dimension(745, 655));
        getContentPane().setLayout(null);

        titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/cadastroclientes.png"))); // NOI18N
        getContentPane().add(titulo);
        titulo.setBounds(420, 50, 600, 100);

        campoNome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/NOME.png"))); // NOI18N
        getContentPane().add(campoNome);
        campoNome.setBounds(340, 220, 80, 40);

        campoEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/EMAIL.png"))); // NOI18N
        getContentPane().add(campoEmail);
        campoEmail.setBounds(340, 270, 90, 40);

        campoEndereco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/ENDEREÇO.png"))); // NOI18N
        getContentPane().add(campoEndereco);
        campoEndereco.setBounds(340, 370, 150, 40);

        campoCep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/CEP.png"))); // NOI18N
        getContentPane().add(campoCep);
        campoCep.setBounds(850, 470, 60, 50);

        campoBairro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/BAIRRO.png"))); // NOI18N
        getContentPane().add(campoBairro);
        campoBairro.setBounds(340, 470, 90, 50);

        campoNumero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/NUMERO.png"))); // NOI18N
        getContentPane().add(campoNumero);
        campoNumero.setBounds(850, 370, 109, 50);

        campoComplemento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/COMPLEMENTO.png"))); // NOI18N
        getContentPane().add(campoComplemento);
        campoComplemento.setBounds(340, 420, 210, 50);

        campoTelefone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/TELEFONE.png"))); // NOI18N
        getContentPane().add(campoTelefone);
        campoTelefone.setBounds(340, 320, 130, 40);

        status.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/status.png"))); // NOI18N
        getContentPane().add(status);
        status.setBounds(950, 540, 100, 50);

        nome.setBackground(java.awt.SystemColor.control);
        getContentPane().add(nome);
        nome.setBounds(450, 230, 710, 30);

        email.setBackground(java.awt.SystemColor.control);
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email);
        email.setBounds(450, 280, 710, 30);

        endereco.setBackground(java.awt.SystemColor.control);
        endereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enderecoActionPerformed(evt);
            }
        });
        getContentPane().add(endereco);
        endereco.setBounds(480, 380, 360, 30);

        bairro.setBackground(java.awt.SystemColor.control);
        getContentPane().add(bairro);
        bairro.setBounds(450, 480, 390, 30);

        complemento.setBackground(java.awt.SystemColor.control);
        getContentPane().add(complemento);
        complemento.setBounds(530, 430, 630, 30);

        numero.setBackground(java.awt.SystemColor.control);
        numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroActionPerformed(evt);
            }
        });
        getContentPane().add(numero);
        numero.setBounds(960, 380, 200, 30);

        cep.setBackground(java.awt.SystemColor.control);
        getContentPane().add(cep);
        cep.setBounds(920, 480, 240, 30);

        telefone.setBackground(java.awt.SystemColor.control);
        getContentPane().add(telefone);
        telefone.setBounds(470, 330, 690, 30);

        datadeNascimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/NASCIMENTO.png"))); // NOI18N
        getContentPane().add(datadeNascimento);
        datadeNascimento.setBounds(340, 540, 120, 40);

        datadeNascimento2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/NASCIMENTO2.png"))); // NOI18N
        getContentPane().add(datadeNascimento2);
        datadeNascimento2.setBounds(470, 550, 170, 30);

        data.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", " " }));
        data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataActionPerformed(evt);
            }
        });
        getContentPane().add(data);
        data.setBounds(650, 550, 70, 30);

        mes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesActionPerformed(evt);
            }
        });
        getContentPane().add(mes);
        mes.setBounds(720, 550, 80, 30);

        ano.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1915", "1916", "1917", "1918", "1919", "1920", "1921", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", " " }));
        ano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anoActionPerformed(evt);
            }
        });
        getContentPane().add(ano);
        ano.setBounds(800, 550, 80, 30);

        voltarAoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotoes/VoltarAoMenuBotao.png"))); // NOI18N
        voltarAoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarAoMenuActionPerformed(evt);
            }
        });
        getContentPane().add(voltarAoMenu);
        voltarAoMenu.setBounds(240, 620, 190, 40);

        cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotoes/cadastrar.png"))); // NOI18N
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrar);
        cadastrar.setBounds(950, 620, 160, 40);

        ativo.setBackground(new java.awt.Color(204, 204, 204));
        ativo.setSelected(true);
        ativo.setText("Ativo");
        ativo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(ativo);
        ativo.setBounds(1060, 540, 100, 20);

        naoAtivo.setBackground(new java.awt.Color(204, 204, 204));
        naoAtivo.setText("Não Ativo");
        naoAtivo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(naoAtivo);
        naoAtivo.setBounds(1060, 560, 100, 21);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/background2.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(735, 644));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1460, 840);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataActionPerformed

    private void voltarAoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarAoMenuActionPerformed
        new PaginaInicialRevendedora().setVisible(true);
        dispose();
    }//GEN-LAST:event_voltarAoMenuActionPerformed

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        

        EnderecoDao cadastrarEndereco = new EnderecoDao();
        ClienteDao cadastrarCliente = new ClienteDao();
        TelefoneDao cadastrarTelefone = new TelefoneDao();
        TratamentoDeErros tratamentoDeErros = new TratamentoDeErros();

        Endereco meuEndereco = new Endereco(this.endereco.getText(), this.bairro.getText(), Integer.parseInt(this.cep.getText()), this.complemento.getText(), this.numero.getText());
        int idEndereco = cadastrarEndereco.cadastrarUmEndereco(meuEndereco);
        tratamentoDeErros.TestarExecao(idEndereco);
        if (idEndereco > 0) {
            meuEndereco.setIdEndereco(idEndereco);
            Telefone meuTelefone = new Telefone(Integer.parseInt(this.telefone.getText()));
            int idTelefone = cadastrarTelefone.cadastrarUmTelefone(meuTelefone);
            tratamentoDeErros.TestarExecao(idTelefone);
            if (idTelefone > 0) {
                meuTelefone.setIdTelefone(idTelefone);
                java.util.Date DataInformada = new java.util.Date(Integer.parseInt(this.ano.getSelectedItem().toString()) - 1900, this.mes.getSelectedIndex(), Integer.parseInt(this.data.getSelectedItem().toString()));
                java.sql.Date dataFinal = new java.sql.Date(DataInformada.getTime());
                
                 
                int radio = 0;
                    if (ativo.isSelected()) {
                        radio = 1;
                        
                      if(naoAtivo.isSelected()){
                          radio = 0;
                      }  
                    }
                    
                

                
                Cliente meuCliente = new Cliente(this.nome.getText(), dataFinal, this.email.getText(), radio, meuEndereco,  Arrays.asList(meuTelefone));
                int idCliente = cadastrarCliente.cadastrarUmCliente(meuCliente);
                tratamentoDeErros.TestarExecao(idCliente);
                if (idCliente > 0) {
                    JOptionPane.showMessageDialog(this, "Cliente cadastrado com sucesso", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                    
                } else {
                    JOptionPane.showMessageDialog(this, "Falha ao cadastrar o Cliente", "Error", JOptionPane.ERROR_MESSAGE);

                }
                limparTela();
                

            }
        }
    }//GEN-LAST:event_cadastrarActionPerformed

    private void enderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enderecoActionPerformed

    private void numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void mesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mesActionPerformed

    private void anoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anoActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ano;
    private javax.swing.JRadioButton ativo;
    private javax.swing.JTextField bairro;
    private javax.swing.JButton cadastrar;
    private javax.swing.JLabel campoBairro;
    private javax.swing.JLabel campoCep;
    private javax.swing.JLabel campoComplemento;
    private javax.swing.JLabel campoEmail;
    private javax.swing.JLabel campoEndereco;
    private javax.swing.JLabel campoNome;
    private javax.swing.JLabel campoNumero;
    private javax.swing.JLabel campoTelefone;
    private javax.swing.JTextField cep;
    private javax.swing.JTextField complemento;
    private javax.swing.JComboBox data;
    private javax.swing.JLabel datadeNascimento;
    private javax.swing.JLabel datadeNascimento2;
    private javax.swing.JTextField email;
    private javax.swing.JTextField endereco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox mes;
    private javax.swing.JRadioButton naoAtivo;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField numero;
    private javax.swing.JLabel status;
    private javax.swing.JTextField telefone;
    private javax.swing.JLabel titulo;
    private javax.swing.JButton voltarAoMenu;
    // End of variables declaration//GEN-END:variables
}

