/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import br.com.integrador.dao.ItensDoPedidoDao;
import br.com.integrador.dao.PedidoDao;
import br.com.integrador.dao.ProdutoDao;
import br.com.integrador.modelos.ItensdoPedido;
import br.com.integrador.modelos.Pedido;
import br.com.integrador.modelos.Produto;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Estefania
 */
public class CadastrarItensdoPedido extends javax.swing.JFrame {

    private final DefaultTableModel modelo = new DefaultTableModel();
    private final DefaultTableModel modelo2 = new DefaultTableModel();
    PedidoDao pedido = new PedidoDao();
    ProdutoDao produtoDao = new ProdutoDao();
    Pedido umPedido = new Pedido();

    /**
     * Creates new form CadastrarItensdoPedido
     */
    public CadastrarItensdoPedido() {
        initComponents();

        setExtendedState(CadastrarItensdoPedido.MAXIMIZED_BOTH);
        modelo.addColumn("Id Produto");
        modelo.addColumn("Nome Produto");
        modelo.addColumn("Descrição");
        modelo.addColumn("Preço");
        modelo.addColumn("Status");
        modelo.addColumn("Nome Fornecedor");

        //List<Produto> resultados = produtoDao.consultarProdutosPorNome(null);
        Tabela.setModel(modelo);
        Tabela.getColumnModel().getColumn(0).setMaxWidth(90);
        Tabela.getColumnModel().getColumn(0).setMinWidth(90);
        Tabela.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        Tabela.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
        Tabela.setModel(modelo);
        Tabela.getColumnModel().getColumn(5).setMaxWidth(0);
        Tabela.getColumnModel().getColumn(5).setMinWidth(0);
        Tabela.getTableHeader().getColumnModel().getColumn(5).setMaxWidth(0);
        Tabela.getTableHeader().getColumnModel().getColumn(5).setMinWidth(0);

        Tabela.getColumnModel().getColumn(1).setMinWidth(90);
        Tabela.getColumnModel().getColumn(1).setMaxWidth(90);

        Tabela.getColumnModel().getColumn(2).setMinWidth(150);
        Tabela.getColumnModel().getColumn(2).setMaxWidth(150);

        Tabela.getColumnModel().getColumn(3).setMinWidth(90);
        Tabela.getColumnModel().getColumn(3).setMaxWidth(90);

        Tabela.getColumnModel().getColumn(4).setMinWidth(90);
        Tabela.getColumnModel().getColumn(4).setMaxWidth(90);

        modelo2.addColumn("IdPedido");
        modelo2.addColumn("Nome Cliente");
        modelo2.addColumn("Valor Pedido Total");
        modelo2.addColumn("Data Pedido");
        modelo2.addColumn("IdCliente");

        List<Pedido> resultados_pedido = new ArrayList<>();

        resultados_pedido = pedido.consultarTodosOsPedido();

        Tabela2.setModel(modelo2);
        Tabela2.getColumnModel().getColumn(0).setMaxWidth(90);
        Tabela2.getColumnModel().getColumn(0).setMinWidth(90);
        Tabela2.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        Tabela2.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
        Tabela2.setModel(modelo2);
        Tabela2.getColumnModel().getColumn(3).setMaxWidth(90);
        Tabela2.getColumnModel().getColumn(3).setMinWidth(90);
        Tabela2.getTableHeader().getColumnModel().getColumn(3).setMaxWidth(0);
        Tabela2.getTableHeader().getColumnModel().getColumn(3).setMinWidth(0);

        Tabela2.getColumnModel().getColumn(1).setMinWidth(150);
        Tabela2.getColumnModel().getColumn(1).setMaxWidth(150);

        Tabela2.getColumnModel().getColumn(2).setMinWidth(150);
        Tabela2.getColumnModel().getColumn(2).setMaxWidth(150);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabela2 = new javax.swing.JTable();
        idPedidoSelecionado = new javax.swing.JTextField();
        nomeClientePedidoSelecionado = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        campoProduto = new javax.swing.JTextField();
        cadastrarItensdoPedido = new javax.swing.JButton();
        voltarAoMenu3 = new javax.swing.JButton();
        campoPedido = new javax.swing.JTextField();
        nomeCliente = new javax.swing.JTextField();
        idPedido1 = new javax.swing.JTextField();
        quantidade = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabela);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(100, 300, 510, 100);

        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        Tabela2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Tabela2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabela2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tabela2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(90, 480, 530, 100);

        idPedidoSelecionado.setEditable(false);
        getContentPane().add(idPedidoSelecionado);
        idPedidoSelecionado.setBounds(620, 300, 110, 30);

        nomeClientePedidoSelecionado.setEditable(false);
        getContentPane().add(nomeClientePedidoSelecionado);
        nomeClientePedidoSelecionado.setBounds(620, 350, 110, 30);

        jButton1.setText("pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(430, 240, 120, 30);

        jButton2.setText("pesquisar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(510, 440, 110, 30);
        getContentPane().add(campoProduto);
        campoProduto.setBounds(100, 240, 310, 30);

        cadastrarItensdoPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotoes/cadastrar.png"))); // NOI18N
        cadastrarItensdoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarItensdoPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrarItensdoPedido);
        cadastrarItensdoPedido.setBounds(1080, 490, 170, 40);

        voltarAoMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotoes/VoltarAoMenuBotao.png"))); // NOI18N
        voltarAoMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarAoMenu3ActionPerformed(evt);
            }
        });
        getContentPane().add(voltarAoMenu3);
        voltarAoMenu3.setBounds(1080, 540, 190, 40);
        getContentPane().add(campoPedido);
        campoPedido.setBounds(200, 440, 290, 30);

        nomeCliente.setEditable(false);
        getContentPane().add(nomeCliente);
        nomeCliente.setBounds(640, 530, 130, 30);

        idPedido1.setEditable(false);
        getContentPane().add(idPedido1);
        idPedido1.setBounds(640, 480, 90, 30);
        getContentPane().add(quantidade);
        quantidade.setBounds(1050, 320, 220, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/titulos/cadastraritens.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(310, 20, 690, 110);

        jLabel3.setFont(new java.awt.Font("Kartika", 1, 14)); // NOI18N
        jLabel3.setText("ID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(740, 300, 50, 30);

        jLabel4.setFont(new java.awt.Font("Kartika", 1, 14)); // NOI18N
        jLabel4.setText("Nome Produto");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(740, 360, 100, 20);

        jLabel5.setFont(new java.awt.Font("Kartika", 1, 14)); // NOI18N
        jLabel5.setText("ID");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(740, 480, 20, 30);

        jLabel6.setFont(new java.awt.Font("Kartika", 1, 14)); // NOI18N
        jLabel6.setText("Nome do Cliente");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(790, 530, 120, 20);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/titulos/quant.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(1070, 290, 180, 20);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/Produtos.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(100, 200, 190, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/pedidos.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(80, 440, 120, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/background2.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, -120, 1690, 1130);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaMouseClicked

        // TODO add your handling code here:
        int linhaselecionada = Tabela.getSelectedRow();

        idPedidoSelecionado.setText(Tabela.getValueAt(linhaselecionada, 0).toString());
        nomeClientePedidoSelecionado.setText(Tabela.getValueAt(linhaselecionada, 1).toString());

    }//GEN-LAST:event_TabelaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ProdutoDao produtos = new ProdutoDao();
        List<Produto> resultados = new ArrayList();
        resultados = produtos.consultarProdutosPorNome((campoProduto.getText()));

        for (Produto produto : resultados) {

            modelo.addRow(new String[]{Integer.toString(produto.getIdProduto()), produto.getNomeProduto(), produto.getDescricao(), Float.toString(produto.getPrecoUnitario()),
                Integer.toString(produto.getStatus()),
                produto.getFornecedor().getNome()
            });

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cadastrarItensdoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarItensdoPedidoActionPerformed

        ItensDoPedidoDao itensDoPedidoDao = new ItensDoPedidoDao();

        Produto meuProduto = new Produto(Integer.parseInt(this.idPedidoSelecionado.getText()));

        Pedido meuPedido = new Pedido(Integer.parseInt(this.idPedidoSelecionado.getText()));

        ItensdoPedido meuItemdoPedido = new ItensdoPedido(meuPedido, meuProduto, Integer.parseInt(this.quantidade.getText()));
        int idItemDoPedido = itensDoPedidoDao.cadastrarItensDoPedido(meuItemdoPedido);

        if (idItemDoPedido > 0) {
            JOptionPane.showMessageDialog(this, "Item do Pedido cadastrado com sucesso", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

        } else {
            JOptionPane.showMessageDialog(this, "Falha ao cadastrar o Item do Pedido", "Error", JOptionPane.ERROR_MESSAGE);

        }

           

    }//GEN-LAST:event_cadastrarItensdoPedidoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        PedidoDao pedidos = new PedidoDao();
        List<Pedido> resultados = new ArrayList();
        resultados = pedidos.consultarPedidoPorNomeCliente((campoPedido.getText()));

        SimpleDateFormat dataFormatada = new SimpleDateFormat("dd/MM/yyyy");
        for (Pedido pedidoresult : resultados) {
            System.out.println("oiiiiiiiii");
            modelo2.addRow(new String[]{Integer.toString(pedidoresult.getIdPedido()), pedidoresult.getCliente().getNome(), Float.toString(pedidoresult.getValorPedidoTotal()),
                dataFormatada.format(pedidoresult.getDataPedido()),
                Integer.toString(pedidoresult.getCliente().getIdCliente())});
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane2MouseClicked

    private void Tabela2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabela2MouseClicked
        // TODO add your handling code here:
        int linhaselecionada = Tabela2.getSelectedRow();
        idPedido1.setText(Tabela2.getValueAt(linhaselecionada, 0).toString());
        nomeCliente.setText(Tabela2.getValueAt(linhaselecionada, 1).toString());
    }//GEN-LAST:event_Tabela2MouseClicked

    private void voltarAoMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarAoMenu3ActionPerformed
        new PaginaInicialRevendedora().setVisible(true);
        dispose();
    }//GEN-LAST:event_voltarAoMenu3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabela;
    private javax.swing.JTable Tabela2;
    private javax.swing.JButton cadastrarItensdoPedido;
    private javax.swing.JTextField campoPedido;
    private javax.swing.JTextField campoProduto;
    private javax.swing.JTextField idPedido1;
    private javax.swing.JTextField idPedidoSelecionado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nomeCliente;
    private javax.swing.JTextField nomeClientePedidoSelecionado;
    private javax.swing.JTextField quantidade;
    private javax.swing.JButton voltarAoMenu3;
    // End of variables declaration//GEN-END:variables
}
