/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import br.com.integrador.dao.FornecedorDao;
import br.com.integrador.dao.ProdutoDao;
import br.com.integrador.execao.TratamentoDeErros;
import br.com.integrador.modelos.Fornecedor;
import br.com.integrador.modelos.Produto;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Estefania
 */
public class CadastrarProduto extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarProduto
     */
    public CadastrarProduto() {
        initComponents();
        carregarCombo();
        setExtendedState(CadastrarProduto.MAXIMIZED_BOTH);

    }
    public void limparTela(){
        campoPreco.setText("");
        campoNomedoProduto.setText("");
        CampoDescricao.setText("");
        fornecedores.setSelectedIndex(-1);
        
        
       
        
        }

    public void carregarCombo() {
        FornecedorDao fornecedorDao = new FornecedorDao();
        List<Fornecedor> resultados = new ArrayList();
        resultados = fornecedorDao.consultarTodosOsFornecedores();

        for (Fornecedor fornecedor : resultados) {
            System.out.println("Nome: " + fornecedor.getNome());
            fornecedores.addItem(fornecedor.getNome());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        nomedoProduto = new javax.swing.JLabel();
        descicao = new javax.swing.JLabel();
        precoUnitario = new javax.swing.JLabel();
        idFornecedor = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        campoPreco = new javax.swing.JTextField();
        campoNomedoProduto = new javax.swing.JTextField();
        fornecedores = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        CampoDescricao = new javax.swing.JTextArea();
        cadastrar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        ativo = new javax.swing.JRadioButton();
        naoAtivo = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(736, 639));
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/titulos/CadastroProdutos.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(270, 50, 630, 80);

        nomedoProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/NomedoProduto.png"))); // NOI18N
        getContentPane().add(nomedoProduto);
        nomedoProduto.setBounds(90, 230, 230, 30);

        descicao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/Descricao.png"))); // NOI18N
        getContentPane().add(descicao);
        descicao.setBounds(100, 470, 150, 50);

        precoUnitario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/precoUnitario.png"))); // NOI18N
        getContentPane().add(precoUnitario);
        precoUnitario.setBounds(90, 350, 210, 30);

        idFornecedor.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        idFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/Fornecedor.png"))); // NOI18N
        getContentPane().add(idFornecedor);
        idFornecedor.setBounds(90, 290, 170, 30);

        status.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/status.png"))); // NOI18N
        getContentPane().add(status);
        status.setBounds(90, 400, 100, 40);

        campoPreco.setBackground(java.awt.SystemColor.control);
        getContentPane().add(campoPreco);
        campoPreco.setBounds(300, 350, 460, 30);

        campoNomedoProduto.setBackground(java.awt.SystemColor.control);
        getContentPane().add(campoNomedoProduto);
        campoNomedoProduto.setBounds(320, 230, 440, 30);

        fornecedores.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECIONE" }));
        fornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fornecedoresActionPerformed(evt);
            }
        });
        getContentPane().add(fornecedores);
        fornecedores.setBounds(290, 290, 470, 30);

        CampoDescricao.setBackground(java.awt.SystemColor.control);
        CampoDescricao.setColumns(20);
        CampoDescricao.setRows(5);
        jScrollPane1.setViewportView(CampoDescricao);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(250, 480, 530, 96);

        cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotoes/cadastrar.png"))); // NOI18N
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrar);
        cadastrar.setBounds(640, 630, 150, 37);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotoes/VoltarAoMenuBotao.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(70, 630, 200, 40);

        ativo.setText("Ativo");
        getContentPane().add(ativo);
        ativo.setBounds(200, 410, 51, 23);

        naoAtivo.setText("Não Ativo");
        getContentPane().add(naoAtivo);
        naoAtivo.setBounds(260, 410, 73, 23);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/LOGOFINALL.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(710, 120, 530, 460);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/background2.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, -60, 1520, 1010);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        FornecedorDao preencherCombo = new FornecedorDao();
        ProdutoDao cadastrarProduto = new ProdutoDao();
        TratamentoDeErros tratamentoDeErros = new TratamentoDeErros();

        Fornecedor meuFornecedor = new Fornecedor(this.fornecedores.getSelectedItem().toString());

        meuFornecedor.setIdFornecedor(preencherCombo.preencheComboBox(meuFornecedor));

        int radio = 0;
        if (ativo.isSelected()) {
            radio = 1;

            if (naoAtivo.isSelected()) {
                radio = 0;
            }
        }

        Produto meuProduto = new Produto(this.campoNomedoProduto.getText(), this.CampoDescricao.getText(), Float.parseFloat(this.campoPreco.getText()), radio, meuFornecedor);
        int idProduto = cadastrarProduto.cadastrarUmProduto(meuProduto);
        tratamentoDeErros.TestarExecao(idProduto);
        if (idProduto > 0) {
            meuProduto.setIdProduto(idProduto);
            if (idProduto > 0) {
                JOptionPane.showMessageDialog(this, "Produto cadastrado com sucesso", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Falha ao cadastrar o Produto", "Error", JOptionPane.ERROR_MESSAGE);

            }
            limparTela();

        }


    }//GEN-LAST:event_cadastrarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new PaginaInicialRevendedora().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void fornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fornecedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fornecedoresActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea CampoDescricao;
    private javax.swing.JRadioButton ativo;
    private javax.swing.JButton cadastrar;
    private javax.swing.JTextField campoNomedoProduto;
    private javax.swing.JTextField campoPreco;
    private javax.swing.JLabel descicao;
    private javax.swing.JComboBox fornecedores;
    private javax.swing.JLabel idFornecedor;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton naoAtivo;
    private javax.swing.JLabel nomedoProduto;
    private javax.swing.JLabel precoUnitario;
    private javax.swing.JLabel status;
    // End of variables declaration//GEN-END:variables
}
