/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import br.com.integrador.dao.ClienteDao;
import br.com.integrador.dao.PedidoDao;
import br.com.integrador.modelos.Cliente;
import br.com.integrador.modelos.Pedido;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Estefania
 */
public class CadastrarPedido extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarPedido
     */
    public CadastrarPedido() {
        initComponents();
        carregarCombo();
        setExtendedState(CadastrarPedido.MAXIMIZED_BOTH);
    }

    public void carregarCombo() {
        ClienteDao clienteDao = new ClienteDao();
        List<Cliente> resultados = new ArrayList();
        resultados = clienteDao.consultarTodosOsClientes();

        for (Cliente cliente : resultados) {
            System.out.println("Nome: " + cliente.getNome());
            nomesDosClientes.addItem(cliente.getNome());
        }
    }
    /*public void limparTela(){
        AnoPedido.setSelectedIndex(-1);
        CampoValor.setText("");
        DiaPedido.setSelectedIndex(-1);
        MesPedido.setSelectedIndex(-1);
        NomesDosClientes.setSelectedIndex(-1);
       
       
       
        
        }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        nomeDoCliente = new javax.swing.JLabel();
        datadoPedido = new javax.swing.JLabel();
        valor = new javax.swing.JLabel();
        diaPedido = new javax.swing.JComboBox();
        mesPedido = new javax.swing.JComboBox();
        anoPedido = new javax.swing.JComboBox();
        campoValor = new javax.swing.JTextField();
        nomesDosClientes = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        voltarAoMenu = new javax.swing.JButton();
        fundo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(642, 662));
        setMinimumSize(new java.awt.Dimension(642, 662));
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/titulos/cadastrodepedidos.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(390, 60, 580, 120);

        nomeDoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/NomedoCliente.png"))); // NOI18N
        getContentPane().add(nomeDoCliente);
        nomeDoCliente.setBounds(50, 300, 240, 40);

        datadoPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/DatadoPedido.png"))); // NOI18N
        getContentPane().add(datadoPedido);
        datadoPedido.setBounds(60, 430, 230, 40);

        valor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/ValordaCompra.png"))); // NOI18N
        getContentPane().add(valor);
        valor.setBounds(50, 360, 242, 40);

        diaPedido.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(diaPedido);
        diaPedido.setBounds(300, 440, 50, 30);

        mesPedido.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Janeiro\t", "Fevereiro\t", "Março\t", "Abril\t", "Maio\t", "Junho\t", "Julho\t", "Agosto\t", "Setembro\t", "Outubro\t", "Novembro\t", "Dezembro\t" }));
        getContentPane().add(mesPedido);
        mesPedido.setBounds(360, 440, 110, 30);

        anoPedido.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1915", "1916", "1917", "1918", "1919", "1920", "1921", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015" }));
        getContentPane().add(anoPedido);
        anoPedido.setBounds(480, 440, 90, 30);

        campoValor.setBackground(java.awt.SystemColor.control);
        getContentPane().add(campoValor);
        campoValor.setBounds(290, 370, 340, 30);

        nomesDosClientes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione o Cliente", " " }));
        getContentPane().add(nomesDosClientes);
        nomesDosClientes.setBounds(290, 310, 340, 30);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotoes/cadastrar.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(480, 530, 160, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/LOGOFINALL.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(710, 160, 690, 490);

        voltarAoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotoes/VoltarAoMenuBotao.png"))); // NOI18N
        voltarAoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarAoMenuActionPerformed(evt);
            }
        });
        getContentPane().add(voltarAoMenu);
        voltarAoMenu.setBounds(40, 530, 190, 40);

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/background2.png"))); // NOI18N
        fundo.setMaximumSize(new java.awt.Dimension(648, 589));
        fundo.setMinimumSize(new java.awt.Dimension(648, 589));
        fundo.setPreferredSize(new java.awt.Dimension(648, 589));
        getContentPane().add(fundo);
        fundo.setBounds(-2, 2, 1440, 930);

        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(210, 240, 34, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       ClienteDao preencherCombo = new ClienteDao();
        PedidoDao cadastrarPedido = new PedidoDao();

        Cliente meuCliente = new Cliente(this.nomesDosClientes.getSelectedItem().toString());
        meuCliente.setIdCliente(preencherCombo.preencheComboBox(meuCliente));
        
        java.util.Date DataInformada = new java.util.Date(Integer.parseInt(this.anoPedido.getSelectedItem().toString()) - 1900, this.mesPedido.getSelectedIndex(), Integer.parseInt(this.diaPedido.getSelectedItem().toString()));
        java.sql.Date dataFinal = new java.sql.Date(DataInformada.getTime());
        Pedido meuPedido = new Pedido(Float.parseFloat(this.campoValor.getText()), dataFinal, meuCliente);
        int idPedido = cadastrarPedido.cadastrarUmPedido(meuPedido);
        if (idPedido > 0) {
            JOptionPane.showMessageDialog(this, "Pedido cadastrado com sucesso", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Falha ao cadastrar o Pedido", "Error", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void voltarAoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarAoMenuActionPerformed
        new PaginaInicialRevendedora().setVisible(true);
        dispose();
    }//GEN-LAST:event_voltarAoMenuActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox anoPedido;
    private javax.swing.JTextField campoValor;
    private javax.swing.JLabel datadoPedido;
    private javax.swing.JComboBox diaPedido;
    private javax.swing.JLabel fundo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox mesPedido;
    private javax.swing.JLabel nomeDoCliente;
    private javax.swing.JComboBox nomesDosClientes;
    private javax.swing.JLabel valor;
    private javax.swing.JButton voltarAoMenu;
    // End of variables declaration//GEN-END:variables
}
