/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import br.com.integrador.dao.FornecedorDao;
import br.com.integrador.modelos.Endereco;
import br.com.integrador.modelos.Telefone;
import br.com.integrador.dao.EnderecoDao;
import br.com.integrador.dao.TelefoneDao;
import br.com.integrador.execao.TratamentoDeErros;
import br.com.integrador.modelos.Fornecedor;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Estefania
 */
public class CadastrarFornecedor extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarFornecedor
     */
    public CadastrarFornecedor() {
        initComponents();
        setExtendedState(CadastrarFornecedor.MAXIMIZED_BOTH);
    }

    public void limparTela() {
        campoNome.setText("");
        campoEmail.setText("");
        campoEndereco.setText("");
        campoComplemento.setText("");
        campoTelefone.setText("");
        campoCep.setText("");
        campoNumero.setText("");
        campoBairro.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        nome = new javax.swing.JLabel();
        telefone = new javax.swing.JLabel();
        endereço = new javax.swing.JLabel();
        bairro = new javax.swing.JLabel();
        cep = new javax.swing.JLabel();
        numero = new javax.swing.JLabel();
        complemento = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        campoTelefone = new javax.swing.JTextField();
        campoBairro = new javax.swing.JTextField();
        campoEndereco = new javax.swing.JTextField();
        campoCep = new javax.swing.JTextField();
        campoNumero = new javax.swing.JTextField();
        campoComplemento = new javax.swing.JTextField();
        campoEmail = new javax.swing.JTextField();
        cadastroFornecedor = new javax.swing.JButton();
        voltarAoMenu = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ativo = new javax.swing.JRadioButton();
        naoAtivo = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(687, 647));
        setPreferredSize(new java.awt.Dimension(687, 647));
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/titulos/cadastrofornecedores.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(380, 40, 620, 130);

        nome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/NOME.png"))); // NOI18N
        getContentPane().add(nome);
        nome.setBounds(50, 240, 80, 60);

        telefone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/TELEFONE.png"))); // NOI18N
        getContentPane().add(telefone);
        telefone.setBounds(50, 490, 110, 50);

        endereço.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/ENDEREÇO.png"))); // NOI18N
        getContentPane().add(endereço);
        endereço.setBounds(40, 350, 130, 30);

        bairro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/BAIRRO.png"))); // NOI18N
        getContentPane().add(bairro);
        bairro.setBounds(50, 440, 100, 40);

        cep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/CEP.png"))); // NOI18N
        getContentPane().add(cep);
        cep.setBounds(480, 440, 70, 40);

        numero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/NUMERO.png"))); // NOI18N
        getContentPane().add(numero);
        numero.setBounds(480, 350, 130, 30);

        complemento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/COMPLEMENTO.png"))); // NOI18N
        getContentPane().add(complemento);
        complemento.setBounds(40, 400, 180, 30);

        email.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/EMAIL.png"))); // NOI18N
        getContentPane().add(email);
        email.setBounds(50, 310, 90, 30);

        status.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/status.png"))); // NOI18N
        getContentPane().add(status);
        status.setBounds(470, 480, 100, 50);

        campoNome.setBackground(java.awt.SystemColor.control);
        getContentPane().add(campoNome);
        campoNome.setBounds(140, 260, 660, 30);

        campoTelefone.setBackground(java.awt.SystemColor.control);
        getContentPane().add(campoTelefone);
        campoTelefone.setBounds(170, 500, 300, 30);

        campoBairro.setBackground(java.awt.SystemColor.control);
        getContentPane().add(campoBairro);
        campoBairro.setBounds(150, 450, 320, 30);

        campoEndereco.setBackground(java.awt.SystemColor.control);
        getContentPane().add(campoEndereco);
        campoEndereco.setBounds(180, 350, 300, 30);

        campoCep.setBackground(java.awt.SystemColor.control);
        getContentPane().add(campoCep);
        campoCep.setBounds(550, 450, 250, 30);

        campoNumero.setBackground(java.awt.SystemColor.control);
        campoNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNumeroActionPerformed(evt);
            }
        });
        getContentPane().add(campoNumero);
        campoNumero.setBounds(590, 350, 210, 30);

        campoComplemento.setBackground(java.awt.SystemColor.control);
        getContentPane().add(campoComplemento);
        campoComplemento.setBounds(220, 400, 580, 30);

        campoEmail.setBackground(java.awt.SystemColor.control);
        getContentPane().add(campoEmail);
        campoEmail.setBounds(140, 310, 660, 30);

        cadastroFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotoes/cadastrar.png"))); // NOI18N
        cadastroFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroFornecedorActionPerformed(evt);
            }
        });
        getContentPane().add(cadastroFornecedor);
        cadastroFornecedor.setBounds(630, 610, 180, 40);

        voltarAoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotoes/VoltarAoMenuBotao.png"))); // NOI18N
        voltarAoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarAoMenuActionPerformed(evt);
            }
        });
        getContentPane().add(voltarAoMenu);
        voltarAoMenu.setBounds(50, 610, 190, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/LOGOFINALL.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(770, 190, 680, 460);

        ativo.setSelected(true);
        ativo.setText("Ativo");
        getContentPane().add(ativo);
        ativo.setBounds(570, 500, 51, 23);

        naoAtivo.setText("Não Ativo");
        getContentPane().add(naoAtivo);
        naoAtivo.setBounds(670, 500, 73, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/background2.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-29, -1, 1470, 880);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarAoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarAoMenuActionPerformed
        new PaginaInicialRevendedora().setVisible(true);
        dispose();
    }//GEN-LAST:event_voltarAoMenuActionPerformed

    private void cadastroFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroFornecedorActionPerformed
        EnderecoDao cadastrarEndereco = new EnderecoDao();
        FornecedorDao cadastrarFornecedor = new FornecedorDao();
        TelefoneDao cadastrarTelefone = new TelefoneDao();
        TratamentoDeErros tratamentoDeErros = new TratamentoDeErros();
        Endereco meuEndereco = new Endereco(this.campoEndereco.getText(), this.campoBairro.getText(), Integer.parseInt(this.campoCep.getText()), this.campoComplemento.getText(), this.campoNumero.getText());
        int idEndereco = cadastrarEndereco.cadastrarUmEndereco(meuEndereco);
        tratamentoDeErros.TestarExecao(idEndereco);
        if (idEndereco > 0) {
            meuEndereco.setIdEndereco(idEndereco);
            Telefone meuTelefone = new Telefone(Integer.parseInt(this.campoTelefone.getText()));
            int idTelefone = cadastrarTelefone.cadastrarUmTelefone(meuTelefone);
            tratamentoDeErros.TestarExecao(idTelefone);
            if (idTelefone > 0) {
                meuTelefone.setIdTelefone(idTelefone);

                List<Telefone> listaTelefones = new ArrayList<>();
                listaTelefones.add(meuTelefone);

                int radio = 0;
                if (ativo.isSelected()) {
                    radio = 1;

                    if (naoAtivo.isSelected()) {
                        radio = 0;
                    }
                }

                Fornecedor meuFornecedor = new Fornecedor(this.campoNome.getText(), this.campoEmail.getText(), radio, meuEndereco, listaTelefones);
                int idFornecedor = cadastrarFornecedor.cadastrarUmFornecedor(meuFornecedor);
                if (idFornecedor > 0) {
                    JOptionPane.showMessageDialog(this, "Fornecedor cadastrado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Falha ao cadastrar o Fornecedor =( ", "Error", JOptionPane.ERROR_MESSAGE);
                }

            }
            limparTela();
        }
    }//GEN-LAST:event_cadastroFornecedorActionPerformed

    private void campoNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNumeroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ativo;
    private javax.swing.JLabel bairro;
    private javax.swing.JButton cadastroFornecedor;
    private javax.swing.JTextField campoBairro;
    private javax.swing.JTextField campoCep;
    private javax.swing.JTextField campoComplemento;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoEndereco;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoNumero;
    private javax.swing.JTextField campoTelefone;
    private javax.swing.JLabel cep;
    private javax.swing.JLabel complemento;
    private javax.swing.JLabel email;
    private javax.swing.JLabel endereço;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton naoAtivo;
    private javax.swing.JLabel nome;
    private javax.swing.JLabel numero;
    private javax.swing.JLabel status;
    private javax.swing.JLabel telefone;
    private javax.swing.JButton voltarAoMenu;
    // End of variables declaration//GEN-END:variables
}
