/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import br.com.integrador.dao.FornecedorDao;
import br.com.integrador.modelos.Fornecedor;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Estefania
 */
public class ConsultarFornecedores extends javax.swing.JFrame {

    private final DefaultTableModel modelo = new DefaultTableModel();
    FornecedorDao fornecedores = new FornecedorDao();

    /**
     * Creates new form PesquisarFornecedores
     */
    public ConsultarFornecedores() {
        initComponents();
        setExtendedState(ConsultarFornecedores.MAXIMIZED_BOTH);
        modelo.addColumn("IdFornecedor");
        modelo.addColumn("Nome");
        modelo.addColumn("Status");

        modelo.addColumn("Email");
        modelo.addColumn("idEndereco");
        modelo.addColumn("Rua");
        modelo.addColumn("Bairro");
        modelo.addColumn("Cep");
        modelo.addColumn("Numero");
        modelo.addColumn("Complemento");

        List<Fornecedor> resultados = new ArrayList<>();

        resultados = fornecedores.consultarTodosOsFornecedores();
        if (resultados.isEmpty()) {
            modelo.addRow(new String[]{"Nenhum resultado cadastrado", null, null, null});

        } else {
            SimpleDateFormat dataFormatada = new SimpleDateFormat("dd/MM/yyy");
            for (Fornecedor fornecedor : resultados) {

            }

            jTable2.setModel(modelo);
            jTable2.getColumnModel().getColumn(0).setMaxWidth(100);
            jTable2.getColumnModel().getColumn(0).setMinWidth(100);
            jTable2.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(100);
            jTable2.getTableHeader().getColumnModel().getColumn(0).setMinWidth(100);
            jTable2.setModel(modelo);
           

            jTable2.getColumnModel().getColumn(1).setMinWidth(100);
            jTable2.getColumnModel().getColumn(1).setMaxWidth(100);

            jTable2.getColumnModel().getColumn(2).setMinWidth(100);
            jTable2.getColumnModel().getColumn(2).setMaxWidth(100);

            jTable2.getColumnModel().getColumn(3).setMinWidth(100);
            jTable2.getColumnModel().getColumn(3).setMaxWidth(100);

            jTable2.getColumnModel().getColumn(4).setMinWidth(100);
            jTable2.getColumnModel().getColumn(4).setMaxWidth(100);

            jTable2.getColumnModel().getColumn(5).setMinWidth(100);
            jTable2.getColumnModel().getColumn(5).setMaxWidth(100);

            jTable2.getColumnModel().getColumn(6).setMinWidth(100);
            jTable2.getColumnModel().getColumn(6).setMaxWidth(100);

            jTable2.getColumnModel().getColumn(7).setMinWidth(100);
            jTable2.getColumnModel().getColumn(7).setMaxWidth(100);

            jTable2.getColumnModel().getColumn(8).setMinWidth(100);
            jTable2.getColumnModel().getColumn(8).setMaxWidth(100);

            jTable2.getColumnModel().getColumn(9).setMinWidth(100);
            jTable2.getColumnModel().getColumn(9).setMaxWidth(100);

            
        }

    }

    private void limparTabela() {
        DefaultTableModel table = new DefaultTableModel();
        table = (DefaultTableModel) jTable2.getModel();
        while (table.getRowCount() > 0) {
            table.removeRow(0);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomePesquisarForn = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        consultar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        voltaraoMenu = new javax.swing.JButton();
        sair = new javax.swing.JButton();
        editarFornecedor = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(nomePesquisarForn);
        nomePesquisarForn.setBounds(90, 220, 830, 40);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 290, 1000, 270);

        consultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotoes/OK.png"))); // NOI18N
        consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarActionPerformed(evt);
            }
        });
        getContentPane().add(consultar);
        consultar.setBounds(990, 220, 60, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/titulos/pesquisarfornecedores.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(290, 40, 670, 100);

        voltaraoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotoes/VoltarAoMenuBotao.png"))); // NOI18N
        voltaraoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltaraoMenuActionPerformed(evt);
            }
        });
        getContentPane().add(voltaraoMenu);
        voltaraoMenu.setBounds(650, 590, 210, 40);

        sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/Sair.png"))); // NOI18N
        getContentPane().add(sair);
        sair.setBounds(920, 590, 90, 40);

        editarFornecedor.setText("Editar");
        editarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarFornecedorActionPerformed(evt);
            }
        });
        getContentPane().add(editarFornecedor);
        editarFornecedor.setBounds(1130, 340, 80, 30);

        jButton2.setText("Excluir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1130, 400, 80, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/background2.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-120, -70, 1760, 990);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarActionPerformed
        // TODO add your handling code here:

        FornecedorDao fornecedor = new FornecedorDao();
        List<Fornecedor> resultados = new ArrayList<>();
        resultados = fornecedor.consultarFornecedorPorNome(nomePesquisarForn.getText());

        for (Fornecedor forn : resultados) {
            modelo.addRow(new String[]{Integer.toString(forn.getIdFornecedor()),
                forn.getNome(), Integer.toString(forn.getStatus()), forn.getEmail(), Integer.toString(forn.getEndereco().getIdEndereco()),
                forn.getEndereco().getRua(),
                forn.getEndereco().getBairro(), Integer.toString(forn.getEndereco().getCep()), forn.getEndereco().getNumero(),
                forn.getEndereco().getComplemento()

            });

        }


    }//GEN-LAST:event_consultarActionPerformed

    private void voltaraoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltaraoMenuActionPerformed
        // TODO add your handling code here:
        new PaginaInicialRevendedora().setVisible(true);
        dispose();
    }//GEN-LAST:event_voltaraoMenuActionPerformed

    private void editarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarFornecedorActionPerformed
        // TODO add your handling code here:
        int linha = jTable2.getSelectedRow();
        int idFornecedor = Integer.parseInt((String) jTable2.getValueAt(linha, 0));
        

        FornecedorDao fornecedorDao = new FornecedorDao();
        Fornecedor fornecedorselecionado = fornecedorDao.consultarFornecedorPorId(idFornecedor);

        AlterarFornecedor alterarFornecedor = new AlterarFornecedor(fornecedorselecionado);
        alterarFornecedor.setVisible(true);
        dispose();


    }//GEN-LAST:event_editarFornecedorActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int linha = jTable2.getSelectedRow();
        int idFornecedor = Integer.parseInt((String) jTable2.getValueAt(linha, 0));
        FornecedorDao fornecedordao = new FornecedorDao();
        int ok = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja desabilitar ?", "Sistema Informa", JOptionPane.YES_NO_OPTION);

        if (ok == JOptionPane.YES_OPTION) {
            fornecedordao.inativarFornecedor(idFornecedor);

        } else {
            ;
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consultar;
    private javax.swing.JButton editarFornecedor;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField nomePesquisarForn;
    private javax.swing.JButton sair;
    private javax.swing.JButton voltaraoMenu;
    // End of variables declaration//GEN-END:variables
}
