/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import br.com.integrador.dao.PedidoDao;
import br.com.integrador.modelos.Pedido;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Estefania,
 */
public class ConsultarPedidos extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarPedidos
     */
    private final DefaultTableModel modelo = new DefaultTableModel();
    PedidoDao pedido = new PedidoDao();

    public ConsultarPedidos() {
        initComponents();
        setExtendedState(ConsultarPedidos.MAXIMIZED_BOTH);

        modelo.addColumn("Nome do Cliente");
        modelo.addColumn("idPedido");
        modelo.addColumn("valorPedidoTotal");
        modelo.addColumn("dataPedido");
        modelo.addColumn("IdCliente");

        List<Pedido> resultados = new ArrayList<>();
        resultados = pedido.consultarTodosOsPedido();
        if (resultados.isEmpty()) {
            modelo.addRow(new String[]{"Nenhum resultado cadastrado", null, null, null});

        } else {
            ;
        }

        Tabela.setModel(modelo);
        Tabela.getColumnModel().getColumn(0).setMaxWidth(150);
        Tabela.getColumnModel().getColumn(0).setMinWidth(150);
        Tabela.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        Tabela.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
        Tabela.setModel(modelo);
        Tabela.getColumnModel().getColumn(3).setMaxWidth(90);
        Tabela.getColumnModel().getColumn(3).setMinWidth(90);
        Tabela.getTableHeader().getColumnModel().getColumn(3).setMaxWidth(0);
        Tabela.getTableHeader().getColumnModel().getColumn(3).setMinWidth(0);

        Tabela.getColumnModel().getColumn(1).setMinWidth(150);
        Tabela.getColumnModel().getColumn(1).setMaxWidth(150);

        Tabela.getColumnModel().getColumn(2).setMinWidth(150);
        Tabela.getColumnModel().getColumn(2).setMaxWidth(150);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        nomePesquisar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        voltaraoMenu = new javax.swing.JButton();
        sair = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/titulos/pesquisarPedidos.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(320, 60, 540, 100);
        getContentPane().add(nomePesquisar);
        nomePesquisar.setBounds(350, 190, 380, 40);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotoes/OK.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(800, 190, 70, 40);

        voltaraoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotoes/VoltarAoMenuBotao.png"))); // NOI18N
        voltaraoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltaraoMenuActionPerformed(evt);
            }
        });
        getContentPane().add(voltaraoMenu);
        voltaraoMenu.setBounds(510, 480, 210, 40);

        sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/Sair.png"))); // NOI18N
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        getContentPane().add(sair);
        sair.setBounds(730, 480, 90, 40);

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(Tabela);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(340, 270, 620, 180);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/background2.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-29, 0, 1670, 850);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        PedidoDao pedidos = new PedidoDao();
        List<Pedido> resultados = new ArrayList();
        resultados = pedidos.consultarPedidoPorNomeCliente(nomePesquisar.getText());

        SimpleDateFormat dataFormatada = new SimpleDateFormat("dd/MM/yyyy");
        for (Pedido pedidoresult : resultados) {
            modelo.addRow(new String[]{pedidoresult.getCliente().getNome(), Integer.toString(pedidoresult.getIdPedido()), Float.toString(pedidoresult.getValorPedidoTotal()),
                dataFormatada.format(pedidoresult.getDataPedido()),
                Integer.toString(pedidoresult.getCliente().getIdCliente())});
            
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        // TODO add your handling code her1e:
        dispose();
    }//GEN-LAST:event_sairActionPerformed

    private void voltaraoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltaraoMenuActionPerformed
        // TODO add your handling code here:
        new PaginaInicialRevendedora().setVisible(true);
        dispose();
    }//GEN-LAST:event_voltaraoMenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabela;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nomePesquisar;
    private javax.swing.JButton sair;
    private javax.swing.JButton voltaraoMenu;
    // End of variables declaration//GEN-END:variables
}
