/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import br.com.integrador.dao.ItensDoPedidoDao;
import br.com.integrador.modelos.ItensdoPedido;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Estefania
 */
public class ConsultarItensDoPedidos extends javax.swing.JFrame {

    private final DefaultTableModel modelo = new DefaultTableModel();
    ItensDoPedidoDao itens = new ItensDoPedidoDao();

    /**
     * Creates new form ConsultarItensDoPedidos
     */
    public ConsultarItensDoPedidos() {
        initComponents();
        setExtendedState(ConsultarItensDoPedidos.MAXIMIZED_BOTH);

        modelo.addColumn("Id Item do Pedido");
        modelo.addColumn("Quantidade");
        modelo.addColumn("Id Produto");
        modelo.addColumn("IdPedido");

        List<ItensdoPedido> resultados = new ArrayList<>();

        resultados = itens.consultarItensDoPedido();
        if (resultados.isEmpty()) {
            modelo.addRow(new String[]{"Nenhum resultado cadastrado", null, null, null});

        } else {
            ;
        }

        Tabela.setModel(modelo);
        Tabela.getColumnModel().getColumn(0).setMaxWidth(150);
        Tabela.getColumnModel().getColumn(0).setMinWidth(150);
        Tabela.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        Tabela.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
        Tabela.setModel(modelo);
        Tabela.getColumnModel().getColumn(3).setMaxWidth(150);
        Tabela.getColumnModel().getColumn(3).setMinWidth(150);
        Tabela.getTableHeader().getColumnModel().getColumn(3).setMaxWidth(0);
        Tabela.getTableHeader().getColumnModel().getColumn(3).setMinWidth(0);

        Tabela.getColumnModel().getColumn(1).setMinWidth(150);
        Tabela.getColumnModel().getColumn(1).setMaxWidth(150);

        Tabela.getColumnModel().getColumn(2).setMinWidth(150);
        Tabela.getColumnModel().getColumn(2).setMaxWidth(150);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomePesquisarItem = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        voltaraoMenu = new javax.swing.JButton();
        excluir = new javax.swing.JButton();
        sair = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(nomePesquisarItem);
        nomePesquisarItem.setBounds(280, 220, 510, 40);

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(Tabela);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(240, 290, 590, 230);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotoes/OK.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(830, 220, 60, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/titulos/pesquisarItensdoPedido.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(280, 90, 770, 90);

        voltaraoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotoes/VoltarAoMenuBotao.png"))); // NOI18N
        voltaraoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltaraoMenuActionPerformed(evt);
            }
        });
        getContentPane().add(voltaraoMenu);
        voltaraoMenu.setBounds(700, 560, 210, 40);

        excluir.setText("Excluir");
        excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });
        getContentPane().add(excluir);
        excluir.setBounds(880, 310, 100, 40);

        sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/Sair.png"))); // NOI18N
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        getContentPane().add(sair);
        sair.setBounds(940, 560, 90, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/background2.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-120, -70, 1760, 990);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/background2.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-2, -16, 1600, 950);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/background2.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-280, 0, 1980, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ItensDoPedidoDao item = new ItensDoPedidoDao();
        List<ItensdoPedido> resultados = new ArrayList();
        resultados = item.consultarItensDoPedidoPorId(Integer.parseInt(nomePesquisarItem.getText()));

        for (ItensdoPedido itens : resultados) {

            modelo.addRow(new String[]{Integer.toString(itens.getIdItensDoPedido()), Integer.toString(itens.getQuantidade()),
                Integer.toString(itens.getProduto().getIdProduto()), Integer.toString(itens.getPedido().getIdPedido())});
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
        // TODO add your handling code here:
        int linha = Tabela.getSelectedRow();
        int idItemPedidos = Integer.parseInt((String) Tabela.getValueAt(linha, 0));
        ItensDoPedidoDao itemdoPedidodao = new ItensDoPedidoDao();
        int ok = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja desabilitar ?", "Sistema Informa", JOptionPane.YES_NO_OPTION);

        if (ok == JOptionPane.YES_OPTION) {
            try {
                itemdoPedidodao.removerItensDoPedido(idItemPedidos);
            } catch (SQLException ex) {
                Logger.getLogger(ConsultarItensDoPedidos.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            ;
        }
    }//GEN-LAST:event_excluirActionPerformed

    private void voltaraoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltaraoMenuActionPerformed
        // TODO add your handling code here:
        new PaginaInicialRevendedora().setVisible(true);
        dispose();
    }//GEN-LAST:event_voltaraoMenuActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_sairActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabela;
    private javax.swing.JButton excluir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nomePesquisarItem;
    private javax.swing.JButton sair;
    private javax.swing.JButton voltaraoMenu;
    // End of variables declaration//GEN-END:variables
}
