/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import br.com.integrador.dao.ProdutoDao;
import br.com.integrador.modelos.Produto;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Estefania
 */
public class ConsultarProdutos extends javax.swing.JFrame {

    private final DefaultTableModel modelo = new DefaultTableModel();
    ProdutoDao produtos = new ProdutoDao();

    public ConsultarProdutos() {
        initComponents();
        setExtendedState(ConsultarProdutos.MAXIMIZED_BOTH);

        modelo.addColumn("IdProduto");
        modelo.addColumn("nome");
        modelo.addColumn("descrição");
        modelo.addColumn("preço");
        modelo.addColumn("status");

        modelo.addColumn("NomeFornecedor");

        List<Produto> resultados = new ArrayList();

        resultados = produtos.consultarTodosOsProdutos();
        if (resultados.isEmpty()) {
            modelo.addRow(new String[]{"Nenhum resultado cadastrado", null, null, null});

        } else {
            ;
        }

        jTable2.setModel(modelo);
        jTable2.getColumnModel().getColumn(0).setMaxWidth(200);
        jTable2.getColumnModel().getColumn(0).setMinWidth(200);
        jTable2.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        jTable2.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
        jTable2.setModel(modelo);
        jTable2.getColumnModel().getColumn(5).setMaxWidth(0);
        jTable2.getColumnModel().getColumn(5).setMinWidth(0);
        jTable2.getTableHeader().getColumnModel().getColumn(5).setMaxWidth(0);
        jTable2.getTableHeader().getColumnModel().getColumn(5).setMinWidth(0);

        jTable2.getColumnModel().getColumn(1).setMinWidth(200);
        jTable2.getColumnModel().getColumn(1).setMaxWidth(200);

        jTable2.getColumnModel().getColumn(2).setMinWidth(200);
        jTable2.getColumnModel().getColumn(2).setMaxWidth(200);

        jTable2.getColumnModel().getColumn(3).setMinWidth(200);
        jTable2.getColumnModel().getColumn(3).setMaxWidth(200);

        jTable2.getColumnModel().getColumn(4).setMinWidth(200);
        jTable2.getColumnModel().getColumn(4).setMaxWidth(200);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        nomePesquisarProduto = new javax.swing.JTextField();
        ok = new javax.swing.JButton();
        excluir = new javax.swing.JButton();
        voltaraoMenu = new javax.swing.JButton();
        sair = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable2);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(200, 270, 890, 310);
        getContentPane().add(nomePesquisarProduto);
        nomePesquisarProduto.setBounds(270, 190, 550, 50);

        ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotoes/OK.png"))); // NOI18N
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        getContentPane().add(ok);
        ok.setBounds(870, 190, 120, 49);

        excluir.setText("Excluir");
        excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });
        getContentPane().add(excluir);
        excluir.setBounds(1160, 390, 90, 40);

        voltaraoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotoes/VoltarAoMenuBotao.png"))); // NOI18N
        voltaraoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltaraoMenuActionPerformed(evt);
            }
        });
        getContentPane().add(voltaraoMenu);
        voltaraoMenu.setBounds(730, 600, 210, 40);

        sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/Sair.png"))); // NOI18N
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        getContentPane().add(sair);
        sair.setBounds(990, 600, 90, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/titulos/pesquisarprodutos.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(350, 80, 710, 110);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/background2.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1650, 890);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
        // TODO add your handling code here:
        int linha = jTable2.getSelectedRow();
        int idProduto = Integer.parseInt((String) jTable2.getValueAt(linha, 0));
        ProdutoDao produtoDao = new ProdutoDao();
        int ok = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja desabilitar ?", "Sistema Informa", JOptionPane.YES_NO_OPTION);

        if (ok == JOptionPane.YES_OPTION) {
            produtoDao.inativarUmProduto(idProduto);

        } else {
            ;
        }
    }//GEN-LAST:event_excluirActionPerformed

    private void voltaraoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltaraoMenuActionPerformed
        // TODO add your handling code here:
        new PaginaInicialRevendedora().setVisible(true);
        dispose();
    }//GEN-LAST:event_voltaraoMenuActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_sairActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        // TODO add your handling code here:
        ProdutoDao produtos = new ProdutoDao();
        List<Produto> resultados = new ArrayList();
        resultados = produtos.consultarProdutosPorNome((nomePesquisarProduto.getText()));

        for (Produto produto : resultados) {

            modelo.addRow(new String[]{Integer.toString(produto.getIdProduto()), produto.getNomeProduto(), produto.getDescricao(), Float.toString(produto.getPrecoUnitario()),
                Integer.toString(produto.getStatus()),
                produto.getFornecedor().getNome()
            });
        }
    }//GEN-LAST:event_okActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton excluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField nomePesquisarProduto;
    private javax.swing.JButton ok;
    private javax.swing.JButton sair;
    private javax.swing.JButton voltaraoMenu;
    // End of variables declaration//GEN-END:variables
}
