/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import br.com.integrador.dao.UsuarioDao;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Estefania
 */
public class LoginRevendedora extends javax.swing.JFrame {

    public String Acesso;

    /**
     * Creates new form LoginRevendedora
     */
    public LoginRevendedora() {
        initComponents();
        setExtendedState(LoginRevendedora.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login = new javax.swing.JLabel();
        senha = new javax.swing.JLabel();
        entrar = new javax.swing.JButton();
        sair = new javax.swing.JButton();
        campoLogin = new javax.swing.JTextField();
        campoSenha = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(478, 472));
        getContentPane().setLayout(null);

        login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/Login.png"))); // NOI18N
        getContentPane().add(login);
        login.setBounds(240, 270, 150, 60);

        senha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/Senha.png"))); // NOI18N
        getContentPane().add(senha);
        senha.setBounds(230, 350, 170, 40);

        entrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/Entrar.png"))); // NOI18N
        entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarActionPerformed(evt);
            }
        });
        entrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                entrarKeyPressed(evt);
            }
        });
        getContentPane().add(entrar);
        entrar.setBounds(590, 410, 120, 40);

        sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/Sair.png"))); // NOI18N
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        getContentPane().add(sair);
        sair.setBounds(230, 520, 90, 40);

        campoLogin.setBackground(java.awt.SystemColor.control);
        getContentPane().add(campoLogin);
        campoLogin.setBounds(330, 290, 380, 30);

        campoSenha.setBackground(java.awt.SystemColor.control);
        campoSenha.setText("jPasswordField1");
        getContentPane().add(campoSenha);
        campoSenha.setBounds(330, 360, 380, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/titulos/LoginLogo.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(410, 180, 320, 90);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/LOGOFINALL.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(640, 110, 680, 470);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/background2.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(505, 501));
        jLabel1.setMinimumSize(new java.awt.Dimension(505, 501));
        jLabel1.setPreferredSize(new java.awt.Dimension(505, 501));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -130, 1440, 1010);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        dispose();
    }//GEN-LAST:event_sairActionPerformed

    private void entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarActionPerformed
        UsuarioDao usuarioDao = new UsuarioDao();
        boolean resposta = false;
        resposta = usuarioDao.consultarUsuario(campoLogin.getText(), campoSenha.getText());

        if (resposta == true) {
            PaginaInicialRevendedora pagina = new PaginaInicialRevendedora();
            pagina.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "LOGIN OU SENHA INVÁLIDOS", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_entrarActionPerformed

    private void entrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_entrarKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            entrar.doClick();
        }
    }//GEN-LAST:event_entrarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginRevendedora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginRevendedora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginRevendedora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginRevendedora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginRevendedora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoLogin;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JButton entrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel login;
    private javax.swing.JButton sair;
    private javax.swing.JLabel senha;
    // End of variables declaration//GEN-END:variables
}
