/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

/**
 *
 * @author Estefania
 */
public class PaginaInicialRevendedora extends javax.swing.JFrame {

    /**
     * Creates new form PaginaInicialRevendedora
     */
    public PaginaInicialRevendedora() {
        initComponents();
        setExtendedState(PaginaInicialRevendedora.MAXIMIZED_BOTH);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadastrarCliente = new javax.swing.JButton();
        cadastrarPedido = new javax.swing.JButton();
        cadastrarProdutos = new javax.swing.JButton();
        cadastrarFornecedor = new javax.swing.JButton();
        sair = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        pesquisarItensDoPedido = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        cadastrarItensDoPedido1 = new javax.swing.JButton();
        relatorios = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(829, 612));
        setMinimumSize(new java.awt.Dimension(829, 612));
        setPreferredSize(new java.awt.Dimension(829, 612));
        getContentPane().setLayout(null);

        cadastrarCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cadastrarCliente.setText("Cadastrar Clientes");
        cadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrarCliente);
        cadastrarCliente.setBounds(80, 300, 280, 30);

        cadastrarPedido.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cadastrarPedido.setText("Cadastrar Pedido");
        cadastrarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrarPedido);
        cadastrarPedido.setBounds(80, 230, 280, 30);

        cadastrarProdutos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cadastrarProdutos.setText("Cadastrar Produtos");
        cadastrarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarProdutosActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrarProdutos);
        cadastrarProdutos.setBounds(80, 430, 280, 30);

        cadastrarFornecedor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cadastrarFornecedor.setText("Cadastrar Fornecedor");
        cadastrarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarFornecedorActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrarFornecedor);
        cadastrarFornecedor.setBounds(80, 370, 280, 30);

        sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/Sair.png"))); // NOI18N
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        getContentPane().add(sair);
        sair.setBounds(1050, 620, 110, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/titulos/bemvindorevendedora.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(380, 10, 600, 160);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/LOGOFINALL.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(720, 40, 580, 510);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("Pesquisar Clientes");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(440, 440, 270, 30);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setText("Pesquisar Fornecedores");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(440, 370, 270, 30);

        pesquisarItensDoPedido.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pesquisarItensDoPedido.setText("Pesquisar Itens do Pedido");
        pesquisarItensDoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarItensDoPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(pesquisarItensDoPedido);
        pesquisarItensDoPedido.setBounds(440, 230, 270, 30);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton7.setText("Pesquisar Pedidos");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(440, 300, 270, 30);

        cadastrarItensDoPedido1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cadastrarItensDoPedido1.setText("Cadastrar Itens Do Pedido");
        cadastrarItensDoPedido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarItensDoPedido1ActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrarItensDoPedido1);
        cadastrarItensDoPedido1.setBounds(80, 490, 280, 30);

        relatorios.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        relatorios.setText("Relatório de Produtos mais vendidos");
        relatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatoriosActionPerformed(evt);
            }
        });
        getContentPane().add(relatorios);
        relatorios.setBounds(440, 500, 270, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/background2.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-140, -40, 1600, 890);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarClienteActionPerformed
        new CadastrarCliente().setVisible(true);
        dispose();
    }//GEN-LAST:event_cadastrarClienteActionPerformed

    private void cadastrarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarFornecedorActionPerformed
        new CadastrarFornecedor().setVisible(true);
        dispose();
    }//GEN-LAST:event_cadastrarFornecedorActionPerformed

    private void cadastrarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarPedidoActionPerformed
        new CadastrarPedido().setVisible(true);
        dispose();
    }//GEN-LAST:event_cadastrarPedidoActionPerformed

    private void cadastrarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarProdutosActionPerformed
        new CadastrarProduto().setVisible(true);
        dispose();
    }//GEN-LAST:event_cadastrarProdutosActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        dispose();
    }//GEN-LAST:event_sairActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new ConsultarFornecedores().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void pesquisarItensDoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarItensDoPedidoActionPerformed
        // TODO add your handling code here:
        new ConsultarItensDoPedidos().setVisible(true);
        dispose();
    }//GEN-LAST:event_pesquisarItensDoPedidoActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        new ConsultarPedidos().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new ConsultarClientes().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void relatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatoriosActionPerformed
        // TODO add your handling code here:
        new Relatorio().setVisible(true);
        dispose();
    }//GEN-LAST:event_relatoriosActionPerformed

    private void cadastrarItensDoPedido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarItensDoPedido1ActionPerformed
        // TODO add your handling code here:
        new CadastrarItensdoPedido().setVisible(true);
        dispose();
    }//GEN-LAST:event_cadastrarItensDoPedido1ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarCliente;
    private javax.swing.JButton cadastrarFornecedor;
    private javax.swing.JButton cadastrarItensDoPedido1;
    private javax.swing.JButton cadastrarPedido;
    private javax.swing.JButton cadastrarProdutos;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton pesquisarItensDoPedido;
    private javax.swing.JButton relatorios;
    private javax.swing.JButton sair;
    // End of variables declaration//GEN-END:variables
}
