/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import br.com.integrador.dao.RelatorioDao;
import br.com.integrador.modelos.Relatorios;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Estefania
 */
public class Relatorio extends javax.swing.JFrame {

    private final DefaultTableModel modelo = new DefaultTableModel();
    RelatorioDao relatorio = new RelatorioDao();

    /**
     * Creates new form Relatorio
     */
    public Relatorio() {
        initComponents();
        setExtendedState(Relatorio.MAXIMIZED_BOTH);
        modelo.addColumn("Produtos");
        modelo.addColumn("Quantidade");
        modelo.addColumn("Total");

        tabelaRelatorio.setModel(modelo);
        tabelaRelatorio.getColumnModel().getColumn(0).setMaxWidth(250);
        tabelaRelatorio.getColumnModel().getColumn(0).setMinWidth(250);
        tabelaRelatorio.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(250);
        tabelaRelatorio.getTableHeader().getColumnModel().getColumn(0).setMinWidth(250);

        tabelaRelatorio.getColumnModel().getColumn(1).setMinWidth(250);
        tabelaRelatorio.getColumnModel().getColumn(1).setMaxWidth(250);

        tabelaRelatorio.getColumnModel().getColumn(2).setMinWidth(250);
        tabelaRelatorio.getColumnModel().getColumn(2).setMaxWidth(250);

    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaRelatorio = new javax.swing.JTable();
        mesCombo = new javax.swing.JComboBox();
        anoCombo = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        voltarAoMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tabelaRelatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabelaRelatorio);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(220, 260, 880, 390);

        mesCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        getContentPane().add(mesCombo);
        mesCombo.setBounds(440, 190, 180, 40);

        anoCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2015", "2016", "2017", "2018", "2019", "2020" }));
        getContentPane().add(anoCombo);
        anoCombo.setBounds(660, 190, 90, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensnomes/relatorios.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(430, 30, 700, 160);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotoes/OK.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(790, 190, 110, 40);

        voltarAoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotoes/VoltarAoMenuBotao.png"))); // NOI18N
        voltarAoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarAoMenuActionPerformed(evt);
            }
        });
        getContentPane().add(voltarAoMenu);
        voltarAoMenu.setBounds(1120, 610, 190, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/background2.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1630, 870);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        List<Relatorios> resultados = new ArrayList();
        int mes = (this.mesCombo.getSelectedIndex()+1);
        int ano = Integer.parseInt(this.anoCombo.getSelectedItem().toString());
        //System.out.println(mes);
        //System.out.println(ano);
        resultados = relatorio.gerarRelatorio(mes, ano);

        for (Relatorios umRelatorio : resultados) {
            modelo.addRow(new String[]{umRelatorio.getItensdopedido().getProduto().getNomeProduto(), String.valueOf(umRelatorio.getIdPedido().getValorPedidoTotal()),
                String.valueOf(umRelatorio.getItensdopedido().getQuantidade())});
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void voltarAoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarAoMenuActionPerformed
        new PaginaInicialRevendedora().setVisible(true);
        dispose();
    }//GEN-LAST:event_voltarAoMenuActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox anoCombo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox mesCombo;
    private javax.swing.JTable tabelaRelatorio;
    private javax.swing.JButton voltarAoMenu;
    // End of variables declaration//GEN-END:variables
}
